config/routes.rb
Rails.application.routes.draw do

  get 'playlists/index'

  get 'playlists/show'

  get 'playlists/new'

  get 'playlists/edit'

  devise_for :users
  root 'movies#index'
  get "/genre/:genre", to: "movies#show_genre", as: "genre"


  resources :accounts do
    member do
      get :add_comment
      get :add_comment_to_account
    end
  end


  resources :movies do
    resources :comments
  end

end

app/models/account.rb
class Account < ApplicationRecord

  belongs_to :user
  has_many :comments 
  has_many :playlists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user 
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :comments
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :accounts
  has_many :comments
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: [:show, :edit, :update]

  def index
    @accounts = current_user.accounts
  end

  def show
    @comments = current_user.comments
  end

  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      redirect_to accounts_path
    else
      render :new
    end
  end

  def udpate
    if @account.update(account_params)
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
  end

  private
    def set_account
      #don't just users Account.find(params[:id]) or you would be able to view
      #others accounts
      @account = current_user.accounts
    end

    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user! 
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected 
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_movie
  before_action :set_comment, only: [:show, :edit, :update, :destroy ]
  before_action :set_user 
  def new
    @comment = Comment.new
  end

  def show
    binding.pry 
  end

  def edit
  end

  def create
    @comment = @movie.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment_name = current_user.first_name
    @user 
    if @comment.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
    binding.pry
  end

  def update
    if @comment.update(comment_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end

    def destroy
      @comment.destroy
      redirect_to movie_comments_path
    end
  end

  private

    def set_user
      @user = current_user
    end 
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def set_comment
        @comment = Comment.find(params[:id])
      end


    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :update, :edit, :destroy]

  def show_genre
    @genre = Movie.where(genre: params[:genre])
  end

  def index
    @movies = Movie.all
  end

  def show
  
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  private
    
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :duration, :genre, :description, :trailer)
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    def index
    @playlists= Playlist.where(account.id) 
  end

  def add_movies
    @movies = Movie.all
  end

  def show
    @playlist = Playlist.find(params[:id])
    @movies = Movie.where(playlist_id: @playlist.id)
  end

  def new
    @playlist = Playlist.new 
  end
  def create
    @playlist = Playlist.new(user_id: current_user.id, name: params["playlist"]["name"])

    if @playlist.save
      redirect_to playlists_path
    else
      render :new
    end

  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy 
    redirect_to playlists_path
  end
  private  
  
  def playlist_params
    params.require(:playlist).permit(:name, :user_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/index.html.erb
<div class=container>
  <h2>Welcome <%= current_user.first_name %>
  </h2>
  <hr />
    <%= link_to "See Comments", account_path(@accounts) %>
    <%= link_to "Playlists", playlists_index_path %>
</div>
<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/accounts/new.html.erb
<h1>Accounts#new</h1>
<p>Find me in app/views/accounts/new.html.erb</p>

app/views/accounts/show.html.erb
<h1>Welcome <%= current_user.first_name %> </h1>

<% @comments.each do |comment| %>
    <div>
      <%= comment.movie.title %>: <%= comment.body %>
    </div>

<% end %>

<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/comments/_comment.html.erb
<hr />

<p><strong> <%= comment.body %></strong></p>
</hr>

app/views/comments/edit.html.erb
<div class="container"><h1>Edit A comment</h1>
<%= form_for [@movie, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.submit %>
<% end %>
</div>
<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/comments/new.html.erb
<div class="container"><h1>Add A comment</h1>
<%= form_for [@movie, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.submit %>
<% end %>
</div>
<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper red darken-4">
    <a href="/" class="brand-logo">uToob</a>
    <ul class="right hide-on-med-and-down">
    <li><%= link_to 'Movies', root_path%></li>
    <li><%= link_to 'Upload', new_movie_path %></li>
    <li><%= link_to 'Account', accounts_path %></li>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>uToob</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>


  </head>

  <body class=>

    <%= render 'layouts/navbar' %>
      <%= yield %>
      
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />

  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <br />

  <%= f.label :duration %>
  <%= f.text_field :duration %>
  <br />

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />

  <%= f.label :trailer %>
  <%= f.text_area :trailer %>
  <br />

  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<h2 class=center>Movies</h2>

   
<div class=container>
  <a class='dropdown-button btn  red darken-4' href='#' data-activates='dropdown1'>Genre</a>
  <ul id='dropdown1' class='dropdown-content'>
    <% genre = @movies.distinct.pluck(:genre) %>
      <% genre.each do |m| %>
        <li>
          <%= link_to m, genre_path(genre: m) %>
        </li>
        <% end %>
  </ul>
  <br /> 
  <div class='row'> 
    <% @movies.each do |movie| %>
      <div class="col s12 m7 l3">
        <div class='card'>
          <div class="card-image">
            <div class="video-container">
              <iframe src="<%= movie.trailer %>"></iframe>
            </div>
          </div>
          <div class="card-content">
            <div class="card-title">
              <h6 class="blue-text text-darken-3"><%= link_to movie.title, movie %></h6>
            </div>
            <p><%= movie.genre %> | <%= movie.duration %></p>
          </div>
        </div>
      </div> 
    <% end %>
  </div>
</div>

<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/movies/new.html.erb
<div class="container">
<h2> Add new movie </h2>
<%= render 'form' %>  
</div>

<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/movies/show.html.erb
<div class="container">
<h2><%= @movie.title %></h2>

<iframe src= "<%= @movie.trailer %> " height=768 width=1024></iframe>

<h6>Genre: <%= @movie.genre %> Duration: <%= @movie.duration %></h6>
<a href="<%= @movie.description %>"> IMDB</a>
<br>
<%= link_to 'Add Comment', new_movie_comment_path(@movie) %>
<h5>Comments</h5>
<% @movie.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
  <%= link_to 'Edit Comment', edit_movie_comment_path(@movie, comment) %>
  <%= link_to 'Delete', [@movie, @comment], method: :delete %>
  <% end %>
<hr />

</div>

<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/movies/show_genre.html.erb
<h2 class=center><%= @genre.first.genre %></h2>
<div class=container>
  <div class='row'>
    <% @genre.each do |movie| %>
      <div class="col s12 m7 l3">
        <div class='card'>
          <div class="card-image">
            <div class="video-container">
              <iframe src="<%= movie.trailer %>"></iframe>
            </div>
          </div>
          <div class="card-content">
            <div class="card-title">
              <h6 class="blue-text text-darken-3">
                <%= link_to movie.title, movie %>
              </h6>
            </div>
            <p>
              <%= movie.genre %> |
                <%= movie.duration %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
  </div>
  <h3>
    <%= link_to 'Back', movies_path %>
  </h3>
</div>

app/views/playlists/edit.html.erb
<h1>Playlists#edit</h1>
<p>Find me in app/views/playlists/edit.html.erb</p>

app/views/playlists/index.html.erb
<h1>Playlists</h1>
<%= link_to "Create New Playlist", playlists_new_path %>
<% @playlists.each do |p| %>
<p><%= link_to p.name, playlist_path(p) %></p>
<% end %>

app/views/playlists/new.html.erb
<h1>Playlists#new</h1>
<p>Find me in app/views/playlists/new.html.erb</p>

app/views/playlists/show.html.erb
<h1>Playlists#show</h1>
<p>Find me in app/views/playlists/show.html.erb</p>